modified profile screen to fit personal account
rice-apps/tunedin pull request #24
Opened 2023-01-21 21:05 UTC by Vivian-Xiao1025

Description: modified profile screen to fit personal account

Tests Performed: n/a

Trello Card Link: https://trello.com/c/JgjrEmPi

<img width="335" alt="Screen Shot 2023-01-21 at 3 03 05 PM" src="https://user-images.githubusercontent.com/67659378/213887054-203a9a21-3f07-480f-8287-5e4660502da8.png">

2023-01-21 21:25 UTC, shreyasminocha commented
Can we adjust this to reduce duplication between the profile and account pages? I suggest moving shared components into separate files, and then importing and using them on both pages.

2023-02-20 21:32 UTC, baylee-rl requested changes
looks great! just a few small comments - i'll go ahead and make them since they overlap w/ #23 and then get both PRs merged

2023-02-20 21:32 UTC, baylee-rl commented on lib/screen/personal_account_screen.dart
> +      // bottomNavigationBar: const MyNavigationBar(),
Remove commented out lines

2023-02-20 21:32 UTC, baylee-rl commented on lib/screen/profile_screen.dart
> +      // bottomNavigationBar: const MyNavigationBar(),
More commented out lines

2023-02-20 21:32 UTC, baylee-rl commented on lib/screen/personal_account_screen.dart
> +                  Column(
[Create followers/following widget.](https://github.com/rice-apps/tunedin/pull/23/files/d4620f4d824072c82404467aefab55cb3be33769#r1083332482)

2023-02-21 02:21 UTC, merged