Set up login flow/user auth (WIP)
rice-apps/tunedin pull request #27
Opened 2023-01-28 21:05 UTC by baylee-rl

Description: 

Tests Performed: tested on android

Trello Card Link: https://trello.com/c/1grF8dyU/14-setup-login-flow-user-auth

2023-01-28 22:47 UTC, baylee-rl commented
this is a draft (working on rewrite using riverpod), but in the meantime, any comments/reviews r still appreciated

2023-02-25 20:40 UTC, shreyasminocha requested changes, later dismissed

2023-02-25 20:40 UTC, shreyasminocha commented on backend/src/routes/auth.ts
> +
Can we remove this line if it's not necessary?

2023-02-25 20:40 UTC, shreyasminocha commented on backend/src/routes/auth.ts
> +
I guess we don't need this any more, right?

2023-02-25 20:40 UTC, shreyasminocha commented on backend/src/routes/auth.ts
> +const CASValidateURL = 'https://idp.rice.edu/idp/profile/cas/serviceValidate';
Nitpick: can we call this `CAS_VALIDATE_URL`?

2023-02-25 20:40 UTC, shreyasminocha commented on backend/src/routes/auth.ts
> +const failureResponse = { success: false, netid: null };
I think we should avoid `netid: null`. Perhaps we could define things such that the client checks the `success` field before attempted to access other fields.

Also, instead of a `success` boolean I think we should have an (optional) `error` field which exists when something goes wrong and includes a description of the error.

2023-02-25 20:40 UTC, shreyasminocha commented on .env.example
> +JWT_SECRET=
I think this secret shouldn't come from the `.env`, but it should be generated in `auth.ts` by generating random bytes and converting them to hex. Then, if we restart the application it will change the secret and invalidate the tokens (which shouldn't be a problem).

We'll have to have some way of dealing with reattempting requests after failed JWT validation (I haven't checked if that already exists).

2023-02-25 20:40 UTC, shreyasminocha commented on lib/main.dart
> +  await dotenv.load(fileName: ".env");
What is this for? If it's just for loading some (non-secret) constants, I think we should just hardcode them on the frontend side. If it's also loading secrets, that's sus. Looks like it's the former. I think we should just move those to `lib/constants.dart`, even the two need to be in sync with the backend.

2023-02-25 20:40 UTC, shreyasminocha commented on lib/screen/login_screen.dart
> +      if (prefs.getString(keyUsername) != null) {
Can we just check for the existence of `keyToken`?

2023-02-25 20:40 UTC, shreyasminocha commented on lib/main.dart
> +import 'package:shared_preferences/shared_preferences.dart';
Can we use [`flutter_secure_storage`](https://pub.dev/packages/flutter_secure_storage) instead? Looks like that's the "correct" way to store sensitive app data.

2023-03-01 06:56 UTC, shreyasminocha reviewed
LGTM. Nice work — this was a big one. Feel free to merge.

2023-03-01 06:56 UTC, shreyasminocha commented on backend/src/routes/auth.ts
> +const crypto = require('crypto');
Small thing, but for consistency can these also be `import ... from ...`?

2023-03-04 19:52 UTC, AhmedA1559 approved these changes
Overall, a few very minute changes needed, but great job with cleanly integrating riverpod authentication and the *headache* that is Rice IDP into the app.

2023-03-04 19:52 UTC, AhmedA1559 commented on android/app/build.gradle
> +    compileSdkVersion 33
Should revert this to not break any tooling in the future

2023-03-04 19:52 UTC, AhmedA1559 commented on android/app/build.gradle
> +        minSdkVersion 19
Same here

2023-03-04 19:52 UTC, AhmedA1559 commented on backend/src/routes/user.ts
> +	user.displayname = 'John Doe';
Let's change this to camelCase (``displayName`` instead)

2023-03-04 20:58 UTC, merged