Refactor like route so that users cannot like the same post multiple times
rice-apps/tunedin pull request #29
Opened 2023-02-04 20:34 UTC by AhmedA1559

Co-authored-by: Talia Frindell <taliafr@users.noreply.github.com>

Description: …

Tests Performed: …

Trello Card Link: …

2023-02-18 19:45 UTC, shreyasminocha commented
Can we take some inspiration from reddit here and have a `/vote` endpoint that takes an integer as a JSON body field?

!["dir indicates the direction of the vote. Voting 1 is an upvote, -1 is a downvote, and 0 is equivalent to "un-voting" by clicking again on a highlighted arrow."](https://user-images.githubusercontent.com/11537232/219885051-6d5a7d4b-21bf-4b12-909c-703c8393e8e2.png)

2023-02-18 20:20 UTC, AhmedA1559 commented
> Can we take some inspiration from reddit here and have a `/vote` endpoint that takes an integer as a JSON body field?
> 
> !["dir indicates the direction of the vote. Voting 1 is an upvote, -1 is a downvote, and 0 is equivalent to "un-voting" by clicking again on a highlighted arrow."](https://user-images.githubusercontent.com/11537232/219885051-6d5a7d4b-21bf-4b12-909c-703c8393e8e2.png)

I think the problem here would be that 

> Can we take some inspiration from reddit here and have a `/vote` endpoint that takes an integer as a JSON body field?
> 
> !["dir indicates the direction of the vote. Voting 1 is an upvote, -1 is a downvote, and 0 is equivalent to "un-voting" by clicking again on a highlighted arrow."](https://user-images.githubusercontent.com/11537232/219885051-6d5a7d4b-21bf-4b12-909c-703c8393e8e2.png)

Would the latest commit work for this?

2023-02-18 21:23 UTC, shreyasminocha commented
Can we get the `dir` from `ctx.request.body` instead? `ctx.params` is for query parameters.

2023-03-25 20:21 UTC, baylee-rl requested changes

2023-03-25 20:21 UTC, baylee-rl commented on backend/src/routes/post.ts
> +	if (ctx.request.body.username) {
can we update this now that auth is merged?

2023-03-25 20:21 UTC, baylee-rl commented on backend/src/routes/post.ts
> +	if (ctx.request.body.username) {
also lint

2023-04-15 18:20 UTC, closed without merging

2023-04-15 18:20 UTC, AhmedA1559 commented
Implementation is now in develop.